version: "3"

services:
    website:
        image: php:apache 
        depends_on:
          - API
        ports:
          - "80:80"
        environment:
          - USERNAME=toto
          - PASSWORD=python
        volumes:
          - ./website:/var/www/html
    API:
        image: myapp:v1
        ports:
          - "5000:5000"
        volumes:
          - ./student_age.json:/data/student_age.json  
          
          
